ERROR - 2025-05-19 05:11:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'modul7_web2', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-19 05:11:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-19 05:43:13 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'modul7_web2', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-19 05:43:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-19 07:13:33 --> mysqli_sql_exception: Duplicate key name 'email' in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Database\Migrations\2025-05-18-121837_CreateUsersTable.php(21): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-19 07:27:16 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `bo...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `bo...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `bo...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `bo...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(754): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Book.php(75): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Book->store()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Book))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-19 07:27:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: books/store]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (:judul:, :penulis:, :penerbit:, :tahun_terbit:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Book.php(75): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Book->store()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Book))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-19 07:27:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (\'Midnights in December\', \'Castlekith\', \'Bukune\', \'2023\', \'2025-05-19 07:27:16\', \'2025-05-19 07:27:16\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (\'Midnights in December\', \'Castlekith\', \'Bukune\', \'2023\', \'2025-05-19 07:27:16\', \'2025-05-19 07:27:16\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (:judul:, :penulis:, :penerbit:, :tahun_terbit:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Book.php(75): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Book->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Book))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-19 07:27:16 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (\'Midnights in December\', \'Castlekith\', \'Bukune\', \'2023\', \'2025-05-19 07:27:16\', \'2025-05-19 07:27:16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (\'Midnights in December\', \'Castlekith\', \'Bukune\', \'2023\', \'2025-05-19 07:27:16\', \'2025-05-19 07:27:16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (\'Midnights in December\', \'Castlekith\', \'Bukune\', \'2023\', \'2025-05-19 07:27:16\', \'2025-05-19 07:27:16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `books` (`judul`, `penulis`, `penerbit`, `tahun_terbit`, `created_at`, `updated_at`) VALUES (:judul:, :penulis:, :penerbit:, :tahun_terbit:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(754): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Book.php(75): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Book->store()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Book))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-19 13:15:55 --> ErrorException: Undefined array key "pengarang"
[Method: GET, Route: dashboard]
in APPPATH\Views\dashboard.php on line 65.
 1 APPPATH\Views\dashboard.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "pengarang"', 'C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\app\\Views\\dashboard.php', 65)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\app\\Views\\dashboard.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('dashboard', [], true)
 5 APPPATH\Controllers\Dashboard.php(18): view('dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-19 13:16:55 --> ErrorException: Undefined array key "tahun"
[Method: GET, Route: dashboard]
in APPPATH\Views\dashboard.php on line 67.
 1 APPPATH\Views\dashboard.php(67): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "tahun"', 'C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\app\\Views\\dashboard.php', 67)
 2 SYSTEMPATH\View\View.php(224): include('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\app\\Views\\dashboard.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('dashboard', [], true)
 5 APPPATH\Controllers\Dashboard.php(18): view('dashboard', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
