ERROR - 2025-05-18 06:54:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-18 06:54:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 06:55:01 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-18 06:55:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 06:55:05 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-18 06:55:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 06:55:09 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-18 06:55:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 06:55:13 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-18 06:55:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 06:55:18 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-18 06:55:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 06:55:27 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-05-18 06:55:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 12:13:47 --> mysqli_sql_exception: Table 'modul7_web2.users' doesn't exist in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2025-05-18 12:13:47 --> Error: Call to a member function getFirstRow() on bool
[Method: POST, Route: login]
in SYSTEMPATH\Model.php on line 330.
 1 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 2 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 12:23:43 --> mysqli_sql_exception: Duplicate key name 'email' in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Database\Migrations\2025-05-18-121837_CreateUsersTable.php(22): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-18 12:30:00 --> mysqli_sql_exception: Unknown table 'modul7_web2.users' in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('DROP TABLE `use...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `use...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `use...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\Forge.php(663): CodeIgniter\Database\BaseConnection->query('DROP TABLE `use...')
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Database\Migrations\2025-05-18-121837_CreateUsersTable.php(27): CodeIgniter\Database\Forge->dropTable('users')
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->down()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(289): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Commands\Database\MigrateRollback.php(101): CodeIgniter\Database\MigrationRunner->regress(0)
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-18 12:30:08 --> mysqli_sql_exception: Duplicate key name 'email' in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Database\Migrations\2025-05-18-121837_CreateUsersTable.php(22): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-18 12:38:48 --> mysqli_sql_exception: Table 'modul7_web2.users' doesn't exist in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2025-05-18 12:38:48 --> Error: Call to a member function getFirstRow() on bool
[Method: POST, Route: login]
in SYSTEMPATH\Model.php on line 330.
 1 SYSTEMPATH\BaseModel.php(717): CodeIgniter\Model->doFirst()
 2 APPPATH\Controllers\Auth.php(21): CodeIgniter\BaseModel->first()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->loginPost()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
ERROR - 2025-05-18 12:42:49 --> mysqli_sql_exception: Unknown table 'modul7_web2.users' in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('DROP TABLE `use...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `use...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `use...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\Forge.php(663): CodeIgniter\Database\BaseConnection->query('DROP TABLE `use...')
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Database\Migrations\2025-05-18-121837_CreateUsersTable.php(27): CodeIgniter\Database\Forge->dropTable('users')
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->down()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(289): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Commands\Database\MigrateRollback.php(101): CodeIgniter\Database\MigrationRunner->regress(0)
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-05-18 12:42:56 --> mysqli_sql_exception: Duplicate key name 'email' in C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\app\Database\Migrations\2025-05-18-121837_CreateUsersTable.php(22): CodeIgniter\Database\Forge->createTable('users')
#5 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(876): App\Database\Migrations\CreateUsersTable->up()
#6 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Praktikum7_DinaIzzatiElfadheya\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-05-18 14:42:38 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Auth.php(62): view('register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 14:53:29 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Auth.php(67): view('register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 14:56:29 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "register.php"
[Method: GET, Route: register]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Auth.php(67): view('register')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 14:56:49 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 14:56:51 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 14:56:53 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 14:57:06 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 14:58:49 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 15:03:16 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 15:10:16 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
CRITICAL - 2025-05-18 15:13:14 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "login.php"
[Method: GET, Route: login]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH\Controllers\Auth.php(11): view('login')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Praktikum7_DinaIzzatiElfadheya\\public\\index.php')
